# Generated by Django 2.0.3 on 2018-03-29 08:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Academics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english', models.IntegerField(default=0, max_length=10)),
                ('maths', models.IntegerField(default=0, max_length=10)),
                ('science', models.IntegerField(default=0)),
                ('evs', models.IntegerField(default=0)),
                ('sst', models.IntegerField(default=0)),
                ('Academic_score', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Details',
            fields=[
                ('st_code', models.IntegerField(default=0, max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('college', models.CharField(max_length=1000)),
                ('Location', models.TextField()),
                ('email', models.EmailField(max_length=70, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='extra_curricular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativities', models.CharField(max_length=100)),
                ('Inter_played', models.IntegerField(default=0)),
                ('Inter_won', models.IntegerField(default=0)),
                ('Intra_played', models.IntegerField(default=0)),
                ('Intra_won', models.IntegerField(default=0)),
                ('activity_score', models.IntegerField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Details')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_code', models.CharField(max_length=100)),
                ('schoolname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Principal', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=70, unique=True)),
                ('contact', models.CharField(max_length=10)),
                ('school_code', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.School')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='sports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sports_played', models.CharField(max_length=100)),
                ('matches', models.IntegerField(default=0)),
                ('semi', models.IntegerField(default=0)),
                ('final', models.IntegerField(default=0)),
                ('won', models.IntegerField(default=0)),
                ('sport_score', models.IntegerField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Details')),
            ],
        ),
        migrations.AddField(
            model_name='academics',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Details'),
        ),
    ]
