# Generated by Django 2.0.3 on 2018-03-31 05:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Academics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eng', models.FloatField(default=0)),
                ('maths', models.FloatField(default=0)),
                ('science', models.FloatField(default=0)),
                ('evs', models.FloatField(default=0)),
                ('sst', models.FloatField(default=0)),
                ('academic_score', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Details',
            fields=[
                ('rollno', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=100)),
                ('acad_year', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('dob', models.DateField(max_length=8)),
                ('teacher_remark', models.TextField(null=True)),
                ('preferred', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='extra_curricular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=100)),
                ('inter_played', models.IntegerField(default=0)),
                ('inter_won', models.IntegerField(default=0)),
                ('intra_played', models.IntegerField(default=0)),
                ('intra_won', models.IntegerField(default=0)),
                ('activity_score', models.FloatField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Details')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('schoolcode', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('schoolname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=70, unique=True)),
                ('contact', models.CharField(max_length=10)),
                ('location', models.TextField(null=True)),
                ('schoolcode', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.School')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='sports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport_name', models.CharField(max_length=100)),
                ('matches', models.IntegerField(default=0)),
                ('semi', models.IntegerField(default=0)),
                ('final', models.IntegerField(default=0)),
                ('won', models.IntegerField(default=0)),
                ('sport_score', models.FloatField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Details')),
            ],
        ),
        migrations.AddField(
            model_name='details',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.School'),
        ),
        migrations.AddField(
            model_name='academics',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Details'),
        ),
    ]
