# Generated by Django 2.0.3 on 2018-03-29 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academics',
            name='english',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='academics',
            name='maths',
            field=models.IntegerField(default=0),
        ),
    ]
