# Generated by Django 2.0.3 on 2018-03-29 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20180329_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='st_code',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
